version: '3'

services:
  php:
    build: ./php/${PHP_VERSION}
    container_name: php_test
    ports:
      - "${HOST_PORT}:80"
      #- "${HOST_SECURE_PORT}:443"
    volumes:
      - ${DOCUMENT_ROOT}:/var/www/html
    links:
      - mysql
    depends_on:
      - mysql

  mysql:
    image: mysql
    container_name: mysql_test
    restart: always
    ports:
      - "${HOST_MYSQL_PORT}:3306"
    volumes:
      - ./db/data:/var/lib/mysql
      - ./db/logs:/var/log/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_ROOT_HOST: '%'
    command: ['mysqld',
      '--default-time-zone=+03:00',
      '--character-set-server=utf8mb4',
      '--collation-server=utf8mb4_unicode_ci',
      '--general-log=${MYSQL_LOG_ENABLE}',
      '--general-log-file=/var/log/mysql/general.log',
      '--default_authentication_plugin=mysql_native_password']
